# Generated by Django 5.2.3 on 2025-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('estudiante', 'Estudiante'), ('admin', 'Administrador')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
