# Generated by Django 5.2.3 on 2025-07-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to='Cursos.usuario'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, to='Cursos.usuario'),
        ),
    ]
