# Generated by Django 5.2.3 on 2025-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_estudiante_usuario_alter_tutor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='link_zoom',
            field=models.URLField(blank=True, null=True),
        ),
    ]
