# Generated by Django 5.2.3 on 2025-07-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_clase_link_zoom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='link_zoom',
            new_name='link_jitsi',
        ),
    ]
