# Generated by Django 5.2.3 on 2025-07-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_rename_link_zoom_clase_link_jitsi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('tutor_materia', 'fecha', 'hora_inicio')},
        ),
    ]
